//! The committed fixture corpus (`docs/spec.md` §20.7, E7a):
//! `crates/swarm-verify/tests/fixtures/*`. This file does two things —
//! proves the committed bytes are reproducible, and proves each fixture
//! produces the verdict its name promises. The negative cases carry the
//! real weight here: a corpus of only clean scenarios would not show the
//! verifier catches anything at all.

#[path = "support/fixture_data.rs"]
mod fixture_data;

use std::fs;
use std::path::PathBuf;

use swarm_core::bundle::{LogBundle, Spec};
use swarm_core::codec::DecodeError;
use swarm_verify::verdict::{ChainProblem, InvariantResult, Witness};
use swarm_verify::verify;

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn committed(name: &str, ext: &str) -> Vec<u8> {
    fs::read(fixtures_dir().join(format!("{name}.{ext}")))
        .unwrap_or_else(|e| panic!("read {name}.{ext}: {e}"))
}

// ---------------------------------------------------------------------------
// Reproducibility: the regenerator (`examples/gen_fixtures.rs`) produces
// exactly the committed bytes.
// ---------------------------------------------------------------------------

#[test]
fn regenerated_fixtures_match_committed_bytes() {
    let cases: Vec<(&str, Vec<u8>, Vec<u8>)> = vec![
        (
            "clean",
            fixture_data::clean().0.encode(),
            fixture_data::clean().1.encode(),
        ),
        (
            "equivocation",
            fixture_data::equivocation().0.encode(),
            fixture_data::equivocation().1.encode(),
        ),
        (
            "overspend",
            fixture_data::overspend().0.encode(),
            fixture_data::overspend().1.encode(),
        ),
        (
            "broken_chain",
            fixture_data::broken_chain().0.encode(),
            fixture_data::broken_chain().1.encode(),
        ),
        (
            "missing_node",
            fixture_data::missing_node().0.encode(),
            fixture_data::missing_node().1.encode(),
        ),
        (
            "truncated",
            fixture_data::truncated_bytes(),
            fixture_data::truncated_spec().encode(),
        ),
    ];

    for (name, bundle_bytes, spec_bytes) in cases {
        assert_eq!(
            bundle_bytes,
            committed(name, "bundle"),
            "{name}.bundle: regenerated bytes differ from the committed fixture"
        );
        assert_eq!(
            spec_bytes,
            committed(name, "spec"),
            "{name}.spec: regenerated bytes differ from the committed fixture"
        );
    }
}

// ---------------------------------------------------------------------------
// Each fixture's promised verdict, read from the committed files — not from
// `fixture_data` — so this exercises exactly what a stranger who only has
// the repo's committed bytes would run.
// ---------------------------------------------------------------------------

fn load(name: &str) -> (LogBundle, Spec) {
    let bundle = LogBundle::decode(&committed(name, "bundle")).expect("decodes");
    let spec = Spec::decode(&committed(name, "spec")).expect("decodes");
    (bundle, spec)
}

#[test]
fn clean_is_satisfied_on_all_four() {
    let (bundle, spec) = load("clean");
    let verdict = verify(&bundle, &spec);
    assert!(verdict.chains.is_empty());
    assert_eq!(verdict.i1, InvariantResult::Satisfied);
    assert_eq!(verdict.i2, InvariantResult::Satisfied);
    assert_eq!(verdict.i3, InvariantResult::Satisfied);
    assert_eq!(verdict.i4, InvariantResult::Satisfied);
    assert!(verdict.all_satisfied());
}

#[test]
fn equivocation_violates_i1() {
    let (bundle, spec) = load("equivocation");
    let verdict = verify(&bundle, &spec);
    match &verdict.i1 {
        InvariantResult::Violated(w) => assert!(matches!(w.as_ref(), Witness::Equivocation(_))),
        other => panic!("expected I1 Violated(Equivocation), got {other:?}"),
    }
}

#[test]
fn overspend_violates_i4() {
    let (bundle, spec) = load("overspend");
    let verdict = verify(&bundle, &spec);
    match &verdict.i4 {
        InvariantResult::Violated(w) => assert!(matches!(w.as_ref(), Witness::Overspend { .. })),
        other => panic!("expected I4 Violated(Overspend), got {other:?}"),
    }
}

#[test]
fn broken_chain_is_a_chain_finding_not_an_invariant_result() {
    let (bundle, spec) = load("broken_chain");
    let verdict = verify(&bundle, &spec);
    assert_eq!(verdict.chains.len(), 1);
    assert!(matches!(verdict.chains[0].error, ChainProblem::Chain(_)));
}

#[test]
fn missing_node_is_undetermined_on_i3() {
    let (bundle, spec) = load("missing_node");
    let verdict = verify(&bundle, &spec);
    assert!(verdict.chains.is_empty());
    assert!(matches!(verdict.i3, InvariantResult::Undetermined(_)));
    assert!(!verdict.any_violated());
}

#[test]
fn truncated_fails_to_decode() {
    let bytes = committed("truncated", "bundle");
    assert_eq!(LogBundle::decode(&bytes), Err(DecodeError::Truncated));
}
